<x-layouts::app :title="$submission->title">
    @include('partials.portal.open')
    <main class="reviewer-page reviewer-detail" aria-labelledby="abstract-title">
        <a class="reviewer-back-link" href="{{ route('reviewer.dashboard') }}">← All abstracts</a>
        <header class="reviewer-detail-header">
            <div><div class="reviewer-detail-title-line"><h1 id="abstract-title">{{ $submission->title }}</h1><span class="reviewer-status reviewer-status--{{ Str::slug($submission->status ?? 'Under Initial Review') }}">{{ $submission->status ?? 'Under Initial Review' }}</span></div><p class="reviewer-detail-meta">{{ $submission->author }} <span aria-hidden="true">·</span> {{ $submission->user?->email ?? 'Email unavailable' }} <span aria-hidden="true">·</span> Submitted {{ $submission->submitted_at?->format('j M Y, H:i') ?? 'date unavailable' }}</p></div>
        </header>
        @if ($submission->attachment_path)
            <section class="reviewer-download-bar" aria-label="Downloads"><div><strong>Attachment</strong><span>{{ $submission->attachment_name ?? basename($submission->attachment_path) }}@if ($attachmentSize), {{ \Illuminate\Support\Number::fileSize($attachmentSize) }}@endif</span></div><a href="{{ route('downloads.attachment', $submission->id) }}" class="reviewer-button reviewer-button--dark">Download attachment</a></section>
        @endif
        <section class="reviewer-detail-section" aria-labelledby="abstract-heading"><h2 id="abstract-heading">Abstract</h2><div class="reviewer-abstract-panel">{{ $submission->abstract }}</div></section>
        <section class="reviewer-detail-section" aria-labelledby="comments-heading"><h2 id="comments-heading">Review comments</h2><div class="reviewer-timeline">@forelse ($submission->reviews->sortBy('created_at') as $review)<article class="reviewer-comment"><div class="reviewer-comment-head"><strong>{{ $review->user?->name ?? 'Reviewer' }}</strong><time datetime="{{ $review->created_at?->toAtomString() }}">{{ $review->created_at?->format('j M Y, H:i') }}</time></div><p>{{ $review->comment }}</p>@if ($review->status)<span class="reviewer-comment-status">Status changed to {{ $review->status }}</span>@endif</article>@empty<p class="reviewer-muted">No review comments yet.</p>@endforelse</div></section>
        <section class="reviewer-comment-form" aria-labelledby="add-comment-heading"><h2 id="add-comment-heading">Add review comment</h2><form method="POST" action="{{ route('reviewer.comment', $submission) }}">@csrf<label for="comment">Comment</label><textarea id="comment" name="comment" rows="6" required aria-describedby="comment-error">{{ old('comment') }}</textarea>@error('comment')<p id="comment-error" class="reviewer-error">{{ $message }}</p>@enderror<div class="reviewer-form-actions"><div><label for="status">Update status</label><select id="status" name="status"><option value="">Keep current status</option>@foreach (['Under Initial Review', 'Rebuttal Open', 'Accepted', 'Revisions Requested', 'Rejected'] as $status)<option value="{{ $status }}" @selected(old('status') === $status)>{{ $status }}</option>@endforeach</select></div><button type="submit" class="reviewer-button reviewer-button--maroon">Send comment</button></div></form></section>
        @if ($previousSubmission || $nextSubmission)<nav class="reviewer-adjacent-nav" aria-label="Adjacent abstracts">@if ($previousSubmission)<a href="{{ route('reviewer.submission.show', $previousSubmission) }}">← Previous abstract</a>@else <span></span>@endif @if ($nextSubmission)<a href="{{ route('reviewer.submission.show', $nextSubmission) }}">Next abstract →</a>@endif</nav>@endif
    </main>
</x-layouts::app>
